import type { Metadata } from 'next'
import { Cairo } from 'next/font/google'
import { ThemeProvider } from '../components/theme-provider'
import './globals.css'
import { ModeToggle } from '../components/mode-toggle'
import Navbar from '../components/navbar/Navbar'
import Footer from '../components/footer/Footer'

const cairoSans = Cairo({
  subsets: ['latin', 'arabic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${cairoSans.className}`} suppressHydrationWarning>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
